title: Tobias Schröder
permalink: /:title/
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "contrast"

plugins:
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single

author:
  name: "Tobias Schröder"
  avatar: "Images/TobiasHelens.jpg"
  location: "Imperial College London"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/tobias_schrdr"

include:
  - assets/css/custom.css
